_wandb:
    value:
        cli_version: 0.25.1
        e:
            y8kr9n2pt81lp5geiyhgdcw7puhbmm3v:
                codePath: src\main.py
                codePathLocal: src\main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1022607298560"
                        used: "555224915968"
                email: teresa.alvarez@student.ie.edu
                executable: C:\Users\alvde\miniconda3\envs\Heart_Disease_Prediction\python.exe
                git:
                    commit: 05902c290a5bac1a28cc679fcf179062e00d761a
                    remote: https://github.com/vik01/mlops-full.git
                host: LAPTOP-79PLF3IL
                memory:
                    total: "16861405184"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\alvde\Desktop\MASTER\TERM 2\MLOPS\GROUP ASSIGMENT\mlops-full\src\main.py
                python: CPython 3.14.3
                root: C:\Users\alvde\Desktop\MASTER\TERM 2\MLOPS\GROUP ASSIGMENT\mlops-full
                startedAt: "2026-03-23T14:03:40.720887Z"
                writerId: y8kr9n2pt81lp5geiyhgdcw7puhbmm3v
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.14.3
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
features:
    value:
        categorical_onehot: []
        min_max_scaler:
            - Age
            - BP
            - Cholesterol
            - Max HR
        n_bins: 3
        numeric_passthrough:
            - id
            - Sex
            - FBS over 120
            - EKG results
            - Exercise angina
            - ST depression
        ordinal_encode:
            - Chest pain type
            - Number of vessels fluro
            - Thallium
            - Slope of ST
        quantile_bin: []
logging:
    value:
        level: INFO
paths:
    value:
        dtrees_model: models/dtrees_model.joblib
        dtrees_predictions: reports/dtrees_predictions.csv
        inference_data: data/inference
        kmeans_model: models/kmeans_model.joblib
        kmeans_predictions: reports/kmeans_predictions.csv
        log_file: logs/pipeline.log
        logit_model: models/logit_model.joblib
        logit_predictions: reports/logit_predictions.csv
        processed_data: data/processed/clean.csv
        raw_data: data/raw/train.csv
problem:
    value:
        problem_type: classification
        target_column: Heart Disease
        valid_targets:
            - Presence
            - Absence
split:
    value:
        random_state: 42
        test_size: 0.2
training:
    value:
        k_means_bins: 3
        max_iterations: 2000
validation:
    value:
        age_max: 120
        age_min: 0
        binary_columns:
            - Sex
            - FBS over 120
            - Exercise angina
        max_null_rate: 0.1
wandb:
    value:
        enabled: true
        entity: ""
        log_predictions: true
        log_processed_data: true
        model_artifact_name: heart_disease_model
        project: heart-disease-mlops
