name: Heart_Disease_Prediction  # Name of the conda environment

channels:
  - conda-forge

dependencies:
  - python>=3.10

  - pip:
    - pandas==3.0.1
    - numpy==2.4.2
    - scikit-learn==1.8.0
    - matplotlib==3.10.8
    - seaborn==0.13.2
    - pytest==9.0.2
    - pyyaml==6.0.3
    - python-dotenv
    - wandb
    - fastapi
    - uvicorn
    - pydantic
    - conda-lock