name: MLOps Quality Gate

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "dev","api-docker"]
  workflow_dispatch:

jobs:
  ci-test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      WANDB_MODE: disabled

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true

      - name: Install conda-lock and create exact environment
        shell: bash -el {0}
        run: |
          conda activate base
          conda install -n base -c conda-forge conda-lock -y
          conda-lock install --name Heart_Disease_Prediction conda-lock.yml

      - name: Run Pytest
        shell: bash -el {0}
        run: |
          conda activate Heart_Disease_Prediction
          pytest -q

      - name: Validate Docker build
        run: docker build -t heart-disease-api:test .